// This file was generated by Prisma.
// Load both .env and .env.local (Next.js convention)
import { config } from 'dotenv'
config()               // loads .env
config({ path: '.env.local' }) // overwrites with .env.local values

import { defineConfig } from 'prisma/config'

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
})
