// AUTO-GENERATED from City of Moreno Valley ArcGIS feature services
// Source: https://services2.arcgis.com/WgPlP3PNKC8Glejs/arcgis/rest/services/MoValParks/FeatureServer
//         https://services2.arcgis.com/WgPlP3PNKC8Glejs/arcgis/rest/services/MoValOtherParks/FeatureServer
// Generated: 2026-08-17 by scripts/build-parks-curated.py
// Re-run after City updates; parser is idempotent and adds no fields below

export type ParkTypeStr = 'PARK' | 'GOLF' | 'REC_CENTER'

export interface CuratedPark {
  slug: string
  name: string
  type: ParkTypeStr
  address: string | null
  city: 'Moreno Valley'
  state: 'CA'
  zip: string | null
  latitude: number | null
  longitude: number | null
  amenities: string[]
  acres: string | number | null
  ada: boolean
  website: string | null
  googlePlaceId: null  // filled by Google Places lookup step
  googleMapUrl: string | null
  cityFeatureId: number  // OBJECTID from MoValParks or MoValOtherParks
  source: 'MoValParks' | 'MoValOtherParks'
  activeNetReservationUrl: string | null
  picUrl: string | null  // City-hosted picture URL (proxy for hero placeholder)
  notes: string | null
}

export const PARKS_CURATED: CuratedPark[] = [
  {
    "source": "MoValParks",
    "cityId": 1,
    "name": "Adrienne Mitchell Memorial Park",
    "address": "22631 Bay Avenue",
    "latitude": 33.91945017618379,
    "longitude": -117.26739842943965,
    "acres": "4.43",
    "ada": true,
    "googleMapUrl": "https://goo.gl/maps/snaYzFkGcy86DAeL9",
    "website": null,
    "amenities": [
      "bbq",
      "basketball",
      "picnic",
      "playground",
      "lights",
      "walking_trails",
      "drinking_fountain",
      "wheelchair_access"
    ],
    "activeNetReservationUrl": "https://anc.apm.activecommunities.com/movalpcs/reservation/search?keyword=Adrienne%20Mitchell%20Memorial%20Park",
    "picUrl": "https://moval.gov/gis/parks/AdrienneMitchell.jpg",
    "notes": null,
    "type": "PARK",
    "slug": "adrienne-mitchell-park",
    "googlePlaceId": null
  },
  {
    "source": "MoValParks",
    "cityId": 2,
    "name": "Bayside Park",
    "address": "24435 Bay Avenue",
    "latitude": 33.92061602402476,
    "longitude": -117.23616239542885,
    "acres": "2.04",
    "ada": true,
    "googleMapUrl": "https://goo.gl/maps/2zAKEQZNtePtzuQT7",
    "website": null,
    "amenities": [
      "bbq",
      "basketball",
      "horseshoe",
      "picnic",
      "playground",
      "lights",
      "drinking_fountain",
      "wheelchair_access"
    ],
    "activeNetReservationUrl": "https://anc.apm.activecommunities.com/movalpcs/reservation/search?keyword=Bayside%20Park",
    "picUrl": "https://moval.gov/gis/parks/Bayside.jpg",
    "notes": null,
    "type": "PARK",
    "slug": "bayside-park",
    "googlePlaceId": null
  },
  {
    "source": "MoValParks",
    "cityId": 3,
    "name": "Bethune Park",
    "address": "16745 Kitching Street",
    "latitude": 33.87785474242339,
    "longitude": -117.2185699829383,
    "acres": "6.00",
    "ada": true,
    "googleMapUrl": "https://goo.gl/maps/YtCtau1RFtEr2d7h9",
    "website": null,
    "amenities": [
      "bbq",
      "parking",
      "picnic",
      "playground",
      "restrooms",
      "lights",
      "snack_bar",
      "baseball",
      "tennis",
      "water_play",
      "drinking_fountain",
      "wheelchair_access"
    ],
    "activeNetReservationUrl": "https://anc.apm.activecommunities.com/movalpcs/reservation/search?keyword=Bethune%20Park",
    "picUrl": "https://moval.gov/gis/parks/Bethune.jpg",
    "notes": null,
    "type": "PARK",
    "slug": "bethune-park",
    "googlePlaceId": null
  },
  {
    "source": "MoValParks",
    "cityId": 4,
    "name": "Celebration Park",
    "address": "14965 Morgan Avenue",
    "latitude": 33.9035309681904,
    "longitude": -117.18146581662259,
    "acres": "6.65",
    "ada": true,
    "googleMapUrl": "https://goo.gl/maps/C4tqJkjnjH91J2YL6",
    "website": null,
    "amenities": [
      "bbq",
      "basketball",
      "parking",
      "picnic",
      "playground",
      "restrooms",
      "lights",
      "walking_trails",
      "water_play",
      "wheelchair_access"
    ],
    "activeNetReservationUrl": "https://anc.apm.activecommunities.com/movalpcs/reservation/search?keyword=Celebration%20Park",
    "picUrl": "https://moval.gov/gis/parks/Celebration.jpg",
    "notes": null,
    "type": "PARK",
    "slug": "celebration-park",
    "googlePlaceId": null
  },
  {
    "source": "MoValParks",
    "cityId": 6,
    "name": "Cottonwood Golf Center",
    "address": "13671 Frederick Street",
    "latitude": 33.92173792071722,
    "longitude": -117.2621998411605,
    "acres": "15.83",
    "ada": true,
    "googleMapUrl": "https://goo.gl/maps/JJnSNEHPgUD6mFYG7",
    "website": null,
    "amenities": [
      "golf_course",
      "meeting_facility",
      "parking",
      "restrooms",
      "lights",
      "wheelchair_access",
      "banquet_facility"
    ],
    "activeNetReservationUrl": "https://anc.apm.activecommunities.com/movalpcs/reservation/search?keyword=Cottonwood%20Golf%20Center",
    "picUrl": "https://moval.gov/gis/parks/CottonwoodGolf.jpg",
    "notes": null,
    "type": "GOLF",
    "slug": "cottonwood-golf-center",
    "googlePlaceId": null
  },
  {
    "source": "MoValParks",
    "cityId": 7,
    "name": "El Potrero Park",
    "address": "16901 Lasselle Street",
    "latitude": 33.874402799053584,
    "longitude": -117.21395787057224,
    "acres": "15.00",
    "ada": true,
    "googleMapUrl": "https://goo.gl/maps/fTDmzSx45v5iNVJdA",
    "website": null,
    "amenities": [
      "bbq",
      "fitness_equipment",
      "athletic_field",
      "parking",
      "picnic",
      "playground",
      "restrooms",
      "lights",
      "soccer",
      "drinking_fountain",
      "wheelchair_access"
    ],
    "activeNetReservationUrl": "https://anc.apm.activecommunities.com/movalpcs/reservation/search?keyword=El%20Potrero%20Park",
    "picUrl": "https://moval.gov/gis/parks/ElPotrero.jpg",
    "notes": null,
    "type": "PARK",
    "slug": "el-potrero-park",
    "googlePlaceId": null
  },
  {
    "source": "MoValParks",
    "cityId": 8,
    "name": "Fairway Park",
    "address": "27891 John F. Kennedy Drive",
    "latitude": 33.90227863723029,
    "longitude": -117.17750438186468,
    "acres": "5.50",
    "ada": true,
    "googleMapUrl": "https://goo.gl/maps/UwAjSWnLzgRGyjpU6",
    "website": null,
    "amenities": [
      "bbq",
      "athletic_field",
      "picnic",
      "playground",
      "restrooms",
      "lights",
      "volleyball",
      "drinking_fountain",
      "wheelchair_access"
    ],
    "activeNetReservationUrl": "https://anc.apm.activecommunities.com/movalpcs/reservation/search?keyword=Fairway%20Park",
    "picUrl": "https://moval.gov/gis/parks/Fairway.jpg",
    "notes": null,
    "type": "PARK",
    "slug": "fairway-park",
    "googlePlaceId": null
  },
  {
    "source": "MoValParks",
    "cityId": 9,
    "name": "Gateway Park",
    "address": "23975 Manzanita Avenue",
    "latitude": 33.96187638546751,
    "longitude": -117.24489714163732,
    "acres": "7.67",
    "ada": true,
    "googleMapUrl": "https://goo.gl/maps/65ib7o8x5iU5ghJt5",
    "website": null,
    "amenities": [
      "bbq",
      "parking",
      "picnic",
      "playground",
      "restrooms",
      "lights",
      "drinking_fountain",
      "wheelchair_access"
    ],
    "activeNetReservationUrl": "https://anc.apm.activecommunities.com/movalpcs/reservation/search?keyword=Gateway%20Park",
    "picUrl": "https://moval.gov/gis/parks/Gateway.jpg",
    "notes": null,
    "type": "PARK",
    "slug": "gateway-park",
    "googlePlaceId": null
  },
  {
    "source": "MoValParks",
    "cityId": 10,
    "name": "Hidden Springs Park",
    "address": "9675 Hidden Springs Drive",
    "latitude": 33.97897528214359,
    "longitude": -117.26904462094413,
    "acres": "7.00",
    "ada": true,
    "googleMapUrl": "https://goo.gl/maps/LT45GXRNzJhfCNCj6",
    "website": null,
    "amenities": [
      "bbq",
      "multi_trail",
      "parking",
      "picnic",
      "playground",
      "walking_trails",
      "wheelchair_access"
    ],
    "activeNetReservationUrl": "https://anc.apm.activecommunities.com/movalpcs/reservation/search?keyword=Hidden%20Springs%20Park",
    "picUrl": "https://moval.gov/gis/parks/HiddenSprings.jpg",
    "notes": null,
    "type": "PARK",
    "slug": "hidden-springs-park",
    "googlePlaceId": null
  },
  {
    "source": "MoValParks",
    "cityId": 11,
    "name": "John F. Kennedy Memorial Park",
    "address": "15115 Indian Street",
    "latitude": 33.901727754959346,
    "longitude": -117.23602307032152,
    "acres": "7.69",
    "ada": true,
    "googleMapUrl": "https://goo.gl/maps/o5J3xRGPQDaGRraE7",
    "website": null,
    "amenities": [
      "bbq",
      "fitness_equipment",
      "parking",
      "picnic",
      "playground",
      "restrooms",
      "lights",
      "baseball",
      "tennis",
      "drinking_fountain",
      "wheelchair_access"
    ],
    "activeNetReservationUrl": "https://anc.apm.activecommunities.com/movalpcs/reservation/search?keyword=John%20F.%20Kennedy%20Park",
    "picUrl": "https://moval.gov/gis/parks/JohnFKennedy.jpg",
    "notes": null,
    "type": "PARK",
    "slug": "john-f-kennedy-park",
    "googlePlaceId": null
  },
  {
    "source": "MoValParks",
    "cityId": 12,
    "name": "Lasselle Sports Park",
    "address": "17155 Lasselle Street",
    "latitude": 33.87220177065815,
    "longitude": -117.21186488219823,
    "acres": "12.75",
    "ada": true,
    "googleMapUrl": "https://goo.gl/maps/Gh2DuN8wdKme6H3k9",
    "website": null,
    "amenities": [
      "bbq",
      "football_field",
      "parking",
      "picnic",
      "playground",
      "restrooms",
      "lights",
      "snack_bar",
      "walking_trails",
      "wheelchair_access"
    ],
    "activeNetReservationUrl": "https://anc.apm.activecommunities.com/movalpcs/reservation/search?keyword=Lasselle%20Sports%20Park",
    "picUrl": "https://moval.gov/gis/parks/LaselleSportsPark.jpg",
    "notes": null,
    "type": "PARK",
    "slug": "lasselle-sports-park",
    "googlePlaceId": null
  },
  {
    "source": "MoValParks",
    "cityId": 13,
    "name": "March Field Park and Valley Skate Park",
    "address": "15415 6th Street",
    "latitude": 33.896734254292795,
    "longitude": -117.24660016056669,
    "acres": "93.32",
    "ada": true,
    "googleMapUrl": "https://goo.gl/maps/QP5vkmnUTFkThfZv6",
    "website": null,
    "amenities": [
      "parking",
      "picnic",
      "restrooms",
      "skate_park",
      "snack_bar",
      "soccer",
      "baseball",
      "wheelchair_access"
    ],
    "activeNetReservationUrl": "https://anc.apm.activecommunities.com/movalpcs/reservation/search?keyword=March%20Field%20Park",
    "picUrl": "https://moval.gov/gis/parks/ValleySkate.jpg",
    "notes": null,
    "type": "PARK",
    "slug": "march-field-park-and-valley-skate-park",
    "googlePlaceId": null
  },
  {
    "source": "MoValParks",
    "cityId": 14,
    "name": "Moreno Valley Community Park",
    "address": "13380 Frederick Street",
    "latitude": 33.92627996651336,
    "longitude": -117.2601439648858,
    "acres": "15.58",
    "ada": true,
    "googleMapUrl": "https://goo.gl/maps/q7b1BgiQtA9svi9o9",
    "website": null,
    "amenities": [
      "bbq",
      "parking",
      "picnic",
      "playground",
      "restrooms",
      "skate_park",
      "soccer",
      "walking_trails",
      "drinking_fountain",
      "wheelchair_access"
    ],
    "activeNetReservationUrl": "https://anc.apm.activecommunities.com/movalpcs/reservation/search?keyword=Moreno%20Valley%20Community%20Park",
    "picUrl": "https://moval.gov/gis/parks/MVCommunity.jpg",
    "notes": null,
    "type": "PARK",
    "slug": "moreno-valley-community-park",
    "googlePlaceId": null
  },
  {
    "source": "MoValParks",
    "cityId": 15,
    "name": "Morrison Park",
    "address": "26667 Dracaea Avenue",
    "latitude": 33.927294676210465,
    "longitude": -117.19797287650185,
    "acres": "14.01",
    "ada": true,
    "googleMapUrl": "https://goo.gl/maps/CtivaPeWNU4ub4GY6",
    "website": null,
    "amenities": [
      "bbq",
      "parking",
      "picnic",
      "restrooms",
      "lights",
      "snack_bar",
      "soccer",
      "baseball",
      "drinking_fountain",
      "wheelchair_access"
    ],
    "activeNetReservationUrl": "https://anc.apm.activecommunities.com/movalpcs/reservation/search?keyword=Morrison%20Park",
    "picUrl": "https://moval.gov/gis/parks/Morrison.jpg",
    "notes": null,
    "type": "PARK",
    "slug": "morrison-park",
    "googlePlaceId": null
  },
  {
    "source": "MoValParks",
    "cityId": 16,
    "name": "Parque Amistad",
    "address": "26160 Gentian Avenue",
    "latitude": 33.896269054141115,
    "longitude": -117.20503204641463,
    "acres": "4.24",
    "ada": true,
    "googleMapUrl": "https://goo.gl/maps/6H6JjyUfg6ACbvwe9",
    "website": null,
    "amenities": [
      "bbq",
      "basketball",
      "picnic",
      "playground",
      "lights",
      "baseball",
      "drinking_fountain",
      "wheelchair_access"
    ],
    "activeNetReservationUrl": "https://anc.apm.activecommunities.com/movalpcs/reservation/search?keyword=Parque%20Amistad",
    "picUrl": "https://moval.gov/gis/parks/ParqueAmistad.jpg",
    "notes": null,
    "type": "PARK",
    "slug": "parque-amistad",
    "googlePlaceId": null
  },
  {
    "source": "MoValParks",
    "cityId": 17,
    "name": "Patriot Park",
    "address": "15310 Perris Boulevard",
    "latitude": 33.898539778690676,
    "longitude": -117.22571694520379,
    "acres": "0.50",
    "ada": true,
    "googleMapUrl": "https://goo.gl/maps/Ksy4eEC4FKUpwHdz6",
    "website": null,
    "amenities": [
      "picnic",
      "playground",
      "lights",
      "walking_trails",
      "wheelchair_access"
    ],
    "activeNetReservationUrl": "https://anc.apm.activecommunities.com/movalpcs/home?onlineSiteId=0&from_original_cui=true",
    "picUrl": "https://moval.gov/gis/parks/Patriot.jpg",
    "notes": null,
    "type": "PARK",
    "slug": "patriot-park",
    "googlePlaceId": null
  },
  {
    "source": "MoValParks",
    "cityId": 18,
    "name": "Pedrorena Park",
    "address": "16009 Rancho Del Lago",
    "latitude": 33.88763056288856,
    "longitude": -117.21404323298212,
    "acres": "5.50",
    "ada": true,
    "googleMapUrl": "https://goo.gl/maps/zfP8o28kACxsfsD79",
    "website": null,
    "amenities": [
      "bbq",
      "basketball",
      "athletic_field",
      "parking",
      "picnic",
      "playground",
      "restrooms",
      "lights",
      "tennis",
      "drinking_fountain",
      "wheelchair_access"
    ],
    "activeNetReservationUrl": "https://anc.apm.activecommunities.com/movalpcs/reservation/search?keyword=Pedrorena%20Park",
    "picUrl": "https://moval.gov/gis/parks/Pedrorena.jpg",
    "notes": null,
    "type": "PARK",
    "slug": "pedrorena-park",
    "googlePlaceId": null
  },
  {
    "source": "MoValParks",
    "cityId": 20,
    "name": "Ridge Crest Park",
    "address": "28506 John F. Kennedy Drive",
    "latitude": 33.90611221099456,
    "longitude": -117.16410898192544,
    "acres": "5.00",
    "ada": true,
    "googleMapUrl": "https://goo.gl/maps/ECDGTVwobQjq8UmZ6",
    "website": null,
    "amenities": [
      "bbq",
      "athletic_field",
      "parking",
      "picnic",
      "playground",
      "restrooms",
      "lights",
      "drinking_fountain",
      "wheelchair_access"
    ],
    "activeNetReservationUrl": "https://anc.apm.activecommunities.com/movalpcs/reservation/search?keyword=Ridge%20Crest%20Park",
    "picUrl": "https://moval.gov/gis/parks/RidgeCrest.jpg",
    "notes": null,
    "type": "PARK",
    "slug": "ridge-crest-park",
    "googlePlaceId": null
  },
  {
    "source": "MoValParks",
    "cityId": 21,
    "name": "Rock Ridge Park",
    "address": "27119 Waterford Way",
    "latitude": 33.931432877716496,
    "longitude": -117.18855266362924,
    "acres": "1.93",
    "ada": true,
    "googleMapUrl": "https://goo.gl/maps/BwB8qoSykp7ZNK2p7",
    "website": null,
    "amenities": [
      "bbq",
      "picnic",
      "playground",
      "lights",
      "wheelchair_access"
    ],
    "activeNetReservationUrl": "https://anc.apm.activecommunities.com/movalpcs/reservation/search?keyword=Rock%20Ridge%20Park",
    "picUrl": "https://moval.gov/gis/parks/RockRidge.jpg",
    "notes": null,
    "type": "PARK",
    "slug": "rock-ridge-park",
    "googlePlaceId": null
  },
  {
    "source": "MoValParks",
    "cityId": 22,
    "name": "Shadow Mountain Park",
    "address": "23680 Presidio Hills Drive",
    "latitude": 33.97848187978552,
    "longitude": -117.25742720524303,
    "acres": "10.00",
    "ada": true,
    "googleMapUrl": "https://goo.gl/maps/c1xafZS8sP7rbV6u9",
    "website": null,
    "amenities": [
      "bbq",
      "parking",
      "picnic",
      "playground",
      "restrooms",
      "lights",
      "baseball",
      "wheelchair_access"
    ],
    "activeNetReservationUrl": "https://anc.apm.activecommunities.com/movalpcs/reservation/search?keyword=Shadow%20Mountain%20Park",
    "picUrl": "https://moval.gov/gis/parks/ShadowMountain.jpg",
    "notes": null,
    "type": "PARK",
    "slug": "shadow-mountain-park",
    "googlePlaceId": null
  },
  {
    "source": "MoValParks",
    "cityId": 23,
    "name": "Sunnymead Park",
    "address": "12655 Perris Boulevard",
    "latitude": 33.936385732533374,
    "longitude": -117.22854788970233,
    "acres": "15.53",
    "ada": true,
    "googleMapUrl": "https://goo.gl/maps/HLp3rXW1QevyzTbq6",
    "website": null,
    "amenities": [
      "bbq",
      "parking",
      "picnic",
      "playground",
      "restrooms",
      "lights",
      "snack_bar",
      "baseball",
      "drinking_fountain",
      "wheelchair_access"
    ],
    "activeNetReservationUrl": "https://anc.apm.activecommunities.com/movalpcs/reservation/search?keyword=Sunnymead%20Park",
    "picUrl": "https://moval.gov/gis/parks/Sunnymead.jpg",
    "notes": null,
    "type": "PARK",
    "slug": "sunnymead-park",
    "googlePlaceId": null
  },
  {
    "source": "MoValParks",
    "cityId": 24,
    "name": "TownGate Memorial Park",
    "address": "13051 Elsworth Street",
    "latitude": 33.930708274425484,
    "longitude": -117.27161870566188,
    "acres": "8.06",
    "ada": true,
    "googleMapUrl": "https://goo.gl/maps/riq5vVUo3oqpSQma6",
    "website": null,
    "amenities": [
      "bbq",
      "athletic_field",
      "parking",
      "picnic",
      "playground",
      "restrooms",
      "lights",
      "baseball",
      "walking_trails",
      "drinking_fountain",
      "wheelchair_access"
    ],
    "activeNetReservationUrl": "https://anc.apm.activecommunities.com/movalpcs/reservation/search?keyword=TownGate",
    "picUrl": "https://moval.gov/gis/parks/TownGateMemorial.jpg",
    "notes": null,
    "type": "PARK",
    "slug": "towngate-park",
    "googlePlaceId": null
  },
  {
    "source": "MoValParks",
    "cityId": 25,
    "name": "Victoriano Park",
    "address": "25730 Los Cabos Drive",
    "latitude": 33.890743661780164,
    "longitude": -117.21268772642219,
    "acres": "5.00",
    "ada": true,
    "googleMapUrl": "https://goo.gl/maps/j1hFxsiHUoc5M7HW6",
    "website": null,
    "amenities": [
      "bbq",
      "athletic_field",
      "parking",
      "picnic",
      "restrooms",
      "lights",
      "drinking_fountain",
      "wheelchair_access"
    ],
    "activeNetReservationUrl": "https://anc.apm.activecommunities.com/movalpcs/reservation/search?keyword=Victoriano%20Park",
    "picUrl": "https://moval.gov/gis/parks/Victoriano.jpg",
    "notes": null,
    "type": "PARK",
    "slug": "victoriano-park",
    "googlePlaceId": null
  },
  {
    "source": "MoValParks",
    "cityId": 26,
    "name": "Vista Lomas Park",
    "address": "26700 Iris Avenue",
    "latitude": 33.895617441131456,
    "longitude": -117.19755640495968,
    "acres": "4.00",
    "ada": true,
    "googleMapUrl": "https://goo.gl/maps/J9Fhf2Tps6fuD4Ao8",
    "website": null,
    "amenities": [
      "bbq",
      "basketball",
      "athletic_field",
      "parking",
      "picnic",
      "playground",
      "lights",
      "baseball",
      "drinking_fountain",
      "wheelchair_access"
    ],
    "activeNetReservationUrl": "https://anc.apm.activecommunities.com/movalpcs/reservation/search?keyword=Vista%20Lomas%20Park",
    "picUrl": "https://moval.gov/gis/parks/VistaLomas.jpg",
    "notes": null,
    "type": "PARK",
    "slug": "vista-lomas-park",
    "googlePlaceId": null
  },
  {
    "source": "MoValParks",
    "cityId": 27,
    "name": "Westbluff Park",
    "address": "10750 Pigeon Pass Road",
    "latitude": 33.96527045011861,
    "longitude": -117.25972312214145,
    "acres": "5.00",
    "ada": true,
    "googleMapUrl": "https://goo.gl/maps/zuX1Ds5qWH5wxNpE6",
    "website": null,
    "amenities": [
      "bbq",
      "parking",
      "picnic",
      "playground",
      "restrooms",
      "lights",
      "walking_trails",
      "drinking_fountain",
      "wheelchair_access"
    ],
    "activeNetReservationUrl": "https://anc.apm.activecommunities.com/movalpcs/reservation/search?keyword=Westbluff%20Park",
    "picUrl": "https://moval.gov/gis/parks/WestBluff.jpg",
    "notes": null,
    "type": "PARK",
    "slug": "westbluff-park",
    "googlePlaceId": null
  },
  {
    "source": "MoValParks",
    "cityId": 28,
    "name": "Weston Park",
    "address": "13170 Lasselle Street",
    "latitude": 33.92902263527094,
    "longitude": -117.20825898625677,
    "acres": "4.14",
    "ada": true,
    "googleMapUrl": "https://goo.gl/maps/pfKo15oU8BgE92h38",
    "website": null,
    "amenities": [
      "bbq",
      "athletic_field",
      "picnic",
      "playground",
      "restrooms",
      "lights",
      "baseball",
      "drinking_fountain",
      "wheelchair_access"
    ],
    "activeNetReservationUrl": "https://anc.apm.activecommunities.com/movalpcs/reservation/search?keyword=Weston%20Park",
    "picUrl": "https://moval.gov/gis/parks/Weston.jpg",
    "notes": null,
    "type": "PARK",
    "slug": "weston-park",
    "googlePlaceId": null
  },
  {
    "source": "MoValParks",
    "cityId": 29,
    "name": "Woodland Park",
    "address": "25705 Cactus Avenue",
    "latitude": 33.90901281142129,
    "longitude": -117.21367650744543,
    "acres": "9.11",
    "ada": true,
    "googleMapUrl": "https://goo.gl/maps/fGeMeVQv8VNTShf28",
    "website": null,
    "amenities": [
      "bbq",
      "basketball",
      "pickleball",
      "picnic",
      "playground",
      "restrooms",
      "lights",
      "baseball",
      "tennis",
      "drinking_fountain",
      "wheelchair_access"
    ],
    "activeNetReservationUrl": "https://anc.apm.activecommunities.com/movalpcs/reservation/search?keyword=Woodland%20Park",
    "picUrl": "https://moval.gov/gis/parks/Woodland.jpg",
    "notes": null,
    "type": "PARK",
    "slug": "woodland-park",
    "googlePlaceId": null
  },
  {
    "source": "MoValParks",
    "cityId": 30,
    "name": "Hidden Springs Passive Nature Park",
    "address": "Hidden Springs Drive and Greenridge Drive",
    "latitude": 33.98081979405105,
    "longitude": -117.26956532311041,
    "acres": "17.00",
    "ada": true,
    "googleMapUrl": "https://goo.gl/maps/B5xf8muQ1wyZy4h9A",
    "website": null,
    "amenities": [
      "picnic",
      "walking_trails",
      "wheelchair_access"
    ],
    "activeNetReservationUrl": "https://anc.apm.activecommunities.com/movalpcs/home?onlineSiteId=0&from_original_cui=true",
    "picUrl": "https://moval.gov/gis/parks/HiddenSpringsPassive.jpg",
    "notes": null,
    "type": "PARK",
    "slug": "hidden-springs-passive-nature-park",
    "googlePlaceId": null
  },
  {
    "source": "MoValParks",
    "cityId": 31,
    "name": "Moreno Valley Equestrian Park & Nature Center",
    "address": "11150 Redlands Boulevard",
    "latitude": 33.959327993681725,
    "longitude": -117.15616899141862,
    "acres": "45.00",
    "ada": true,
    "googleMapUrl": "https://goo.gl/maps/fszmhwh6kScT2fs98",
    "website": null,
    "amenities": [
      "equestrian",
      "parking",
      "walking_trails",
      "wheelchair_access"
    ],
    "activeNetReservationUrl": "https://anc.apm.activecommunities.com/movalpcs/home?onlineSiteId=0&from_original_cui=true",
    "picUrl": "https://moval.gov/gis/parks/EquestrianCenter.jpg",
    "notes": null,
    "type": "PARK",
    "slug": "moreno-valley-equestrian-park",
    "googlePlaceId": null
  },
  {
    "source": "MoValParks",
    "cityId": 32,
    "name": "Hound Town Dog Park",
    "address": "11150 Redlands Boulevard",
    "latitude": 33.95792641055866,
    "longitude": -117.15312200209422,
    "acres": "0.25",
    "ada": true,
    "googleMapUrl": "https://goo.gl/maps/A751QkV3oDCBfodZ6",
    "website": null,
    "amenities": [
      "dog_park",
      "parking",
      "wheelchair_access"
    ],
    "activeNetReservationUrl": "https://anc.apm.activecommunities.com/movalpcs/home?onlineSiteId=0&from_original_cui=true",
    "picUrl": "https://moval.gov/gis/parks/HoundTown.jpg",
    "notes": null,
    "type": "PARK",
    "slug": "hound-town-dog-park",
    "googlePlaceId": null
  },
  {
    "source": "MoValParks",
    "cityId": 33,
    "name": "TownGate II Park",
    "address": "13100 Arbor Park Lane",
    "latitude": 33.92989088742496,
    "longitude": -117.2739216572673,
    "acres": "8.91",
    "ada": true,
    "googleMapUrl": "https://goo.gl/maps/3B4sxpxaHBiwoA96A",
    "website": null,
    "amenities": [
      "bbq",
      "parking",
      "picnic",
      "playground",
      "lights",
      "walking_trails",
      "wheelchair_access",
      "banquet_facility"
    ],
    "activeNetReservationUrl": "https://anc.apm.activecommunities.com/movalpcs/reservation/search?keyword=TownGate",
    "picUrl": "https://moval.gov/gis/parks/TownGateII.jpg",
    "notes": null,
    "type": "PARK",
    "slug": "towngate-ii-park",
    "googlePlaceId": null
  },
  {
    "source": "MoValParks",
    "cityId": 34,
    "name": "Santiago Park",
    "address": "24731 Tiger Avenue",
    "latitude": 33.89228221878414,
    "longitude": -117.23156236751551,
    "acres": "2.84",
    "ada": true,
    "googleMapUrl": "https://goo.gl/maps/PaixvTZS5x454QWD6",
    "website": null,
    "amenities": [
      "bbq",
      "basketball",
      "fitness_equipment",
      "multi_field",
      "picnic",
      "playground",
      "restrooms",
      "lights",
      "walking_trails",
      "wheelchair_access"
    ],
    "activeNetReservationUrl": "https://anc.apm.activecommunities.com/movalpcs/reservation/search?keyword=Santiago%20Park",
    "picUrl": "https://moval.gov/gis/parks/Santiago.jpg",
    "notes": null,
    "type": "PARK",
    "slug": "santiago-park",
    "googlePlaceId": null
  },
  {
    "source": "MoValParks",
    "cityId": 35,
    "name": "Civic Center Amphitheater & Park",
    "address": "14075 Frederick Street",
    "latitude": 33.91619561304287,
    "longitude": -117.26336520042591,
    "acres": " ",
    "ada": true,
    "googleMapUrl": "https://goo.gl/maps/Y2yqi9hsBX6rfwYz6",
    "website": null,
    "amenities": [
      "parking",
      "lights",
      "walking_trails",
      "wheelchair_access"
    ],
    "activeNetReservationUrl": "https://anc.apm.activecommunities.com/movalpcs/reservation/search/detail/442",
    "picUrl": "https://moval.gov/gis/parks/Amphitheater.jpg",
    "notes": null,
    "type": "REC_CENTER",
    "slug": "civic-center-amphitheater-and-park",
    "googlePlaceId": null
  },
  {
    "source": "MoValParks",
    "cityId": 36,
    "name": "Windsong Park",
    "address": "13970 Azure Street",
    "latitude": 33.91777368315058,
    "longitude": -117.20517101848404,
    "acres": "1.80",
    "ada": false,
    "googleMapUrl": "https://maps.app.goo.gl/xmFdq5xfs9A4Peu69",
    "website": null,
    "amenities": [
      "bbq",
      "benches",
      "fitness_equipment",
      "picnic",
      "playground",
      "lights",
      "walking_trails",
      "drinking_fountain"
    ],
    "activeNetReservationUrl": "https://anc.apm.activecommunities.com/movalpcs/home?onlineSiteId=0&from_original_cui=true",
    "picUrl": "https://moval.gov/gis/parks/Windsong.jpg",
    "notes": null,
    "type": "PARK",
    "slug": "windsong-park",
    "googlePlaceId": null
  },
  {
    "source": "MoValParks",
    "cityId": 37,
    "name": "College Park",
    "address": "16130 Lasselle Street",
    "latitude": 33.88497212975553,
    "longitude": -117.19890581203916,
    "acres": "25",
    "ada": false,
    "googleMapUrl": "https://www.google.com/maps/place/College+Park/@33.8849012,-117.211327,15z/data=!4m6!3m5!1s0x80dca7cf763edf0d:0x732ebb5375bded94!8m2!3d33.8849007!4d-117.2010286!16s%2Fg%2F11sjgw1vth?entry=ttu&g_ep=EgoyMDI1MDkwMi4wIKXMDSoASAFQAw%3D%3D",
    "website": null,
    "amenities": [
      "playground",
      "lights",
      "soccer"
    ],
    "activeNetReservationUrl": "https://anc.apm.activecommunities.com/movalpcs/reservation/search?keyword=Vista%20Lomas%20Park",
    "picUrl": "https://moval.gov/gis/parks/collegepark.jpg",
    "notes": null,
    "type": "PARK",
    "slug": "college-park",
    "googlePlaceId": null
  },
  {
    "source": "MoValOtherParks",
    "cityId": 1,
    "name": "Veterans Memorial",
    "address": "14075 Frederick St",
    "latitude": 33.91556792483796,
    "longitude": -117.26301590849395,
    "amenities": [],
    "acres": null,
    "ada": false,
    "website": "https://moval.gov/community/monument.shtml",
    "googlePlaceId": null,
    "googleMapUrl": null,
    "cityFeatureId": 1,
    "activeNetReservationUrl": null,
    "picUrl": "https://moval.gov/gis/parks/VeteransMemorial.jpg",
    "notes": null,
    "type": "PARK",
    "slug": "veterans-memorial"
  }
]
